definitions:
  response.PingResponse:
    properties:
      current_date:
        type: string
      message: {}
      status:
        type: string
    type: object
host: 127.0.0.1:80
info:
  contact: {}
  description: Template untuk inisiasi seluruh backend project pada ULaMM menggunakan
    bahasa pemrograman Go
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Template-Backend-ULaMM-Go
  version: "1.0"
paths:
  /health:
    get:
      description: Melakukan ping ke database untuk memeriksa kesehatan aplikasi dan
        database
      operationId: get-ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PingResponse'
        "500":
          description: Internal Server Error
      summary: Ping
      tags:
      - ping
swagger: "2.0"
